name: Deploy Task Tracker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Lambda package
        working-directory: projects/02-notice-board
        run: python build-lambda-pkg.py

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://projects/02-notice-board/backend/lambda.zip

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: projects/02-notice-board/frontend
        run: npm install

      - name: Build frontend
        working-directory: projects/02-notice-board/frontend
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Upload frontend to S3
        run: |
          aws s3 sync projects/01-task-tracker/frontend/dist/ s3://${{ secrets.S3_BUCKET }} --delete